[project]
name = "small-test"
authors = [
  { name="Aggelos Arelakis", email="aggelosarelakis@gmail.com" },
]
version = "0.1.0"
description = "A small library/framework used for testing your source code."

readme = "README.md"
requires-python = ">=3.13"
dependencies = []

classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

license = "MIT"
license-files = ["LICEN[CS]E*"]


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
