
[project]
name = "tINI-test"
authors = [
  { name="Aggelos Arelakis", email="aggelosarelakis@gmail.com" },
]
version = "0.2.0"
description = "A small library/framework used for testing your python source code."

readme = "README.md"
requires-python = ">=3.10"
dependencies = []

classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

license = "MIT"
license-files = ["LICEN[CS]E*"]


[project.urls]
Homepage = "https://github.com/AggelosAr/tini_test"


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[tool.hatch.build.targets.wheel]
packages = ["src/tini_test"]


