
from tini_test.mock import Mock
from tini_test.must_equals import must_equal
from tini_test.test_utils import Test

from tini_test.shared import Shared, var



def empty_shared_are_ignored_p(): ...

def empty_shared_are_ignored_n_p(): ...



def shared_accepts_valid_arguments(): ...

def shared_rejects_keyword_arguments(): ...

def shared_rejects_same_variable_name(): ...

def shared_initializes_shared_variable(): ...

def shared_allows_modification_of_shared_variable(): ...




def usage_of_non_declared_shared_variable_raises_setup(): ...

def usage_of_non_declared_shared_variable_raises_main(): ...

def usage_of_non_declared_shared_variable_raises_cleanup(): ...



def var_mod_in_setup_persists_in_main_cleanup(): ...

def var_mod_in_main_persists_in_cleanup(): ...

def var_mod_in_setup_and_main(): ...


def var_mod_in_main_does_not_exist_in_setup(): ...

def var_mod_in_cleanup_does_not_exist_in_setup_and_main(): ...


def unused_shared_variable(): ...
