name: API workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test cov

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install requirements
        run: |
          pip install tINI-test
          pip install coverage

      - name: Run tests and collect coverage
        run: |
          coverage run -m tini_test -r async

      - name: Generate coverage report
        run: |
          coverage xml -o coverage-service.xml

      - name: Upload coverage reports to Codecov
        run: |
          curl -Os https://cli.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov --verbose upload-process \
            -t ${{ secrets.CODECOV_TOKEN }} \
            -n service-${{ github.run_id }} \
            -F service \
            -f coverage-service.xml
